name: Format

on:
  pull_request:
     - main
     - develop
     - master

jobs:
  code:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install dependencies
        uses: './.github/actions/install-deps'

      - name: Run Biome
        run: pnpm format:check
