name: Lint

on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install dependencies
        uses: './.github/actions/install-deps'

      - name: Run Biome Lint
        run: pnpm lint
